### ISSUE TITLE
"Internal Server Error" after Login

### ISSUE THREAD

**Issue by ghost** [sonicnkt/glauth-ui#27]
Hi. 

I recently installed a new GLAuth instance (Alpine 3.18, running & tested) with glauth-ui (latest). glauth-ui shows Login-Page. After Login I get "Internal Server Error" page. 

Docker Logs:

`glauthui  | /home/ldap/app/__init__.py:23: UserWarning: For Bootstrap 4, please import and use "Bootstrap4" class, the "Bootstrap" class is deprecated and will be removed in 3.0.
glauthui  |   bootstrap = Bootstrap(app)
glauthui  | [2023-06-18 08:51:23,040] INFO in __init__: Glauth UI
glauthui  | Traceback (most recent call last):
glauthui  |   File "/home/ldap/venv/bin/flask", line 8, in <module>
glauthui  |     sys.exit(main())
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask/cli.py", line 994, in main
glauthui  |     cli.main(args=sys.argv[1:])
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask/cli.py", line 600, in main
glauthui  |     return super().main(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
glauthui  |     rv = self.invoke(ctx)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
glauthui  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
glauthui  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
glauthui  |     return ctx.invoke(self.callback, **ctx.params)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
glauthui  |     return __callback(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
glauthui  |     return f(get_current_context(), *args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask/cli.py", line 444, in decorator
glauthui  |     return __ctx.invoke(f, *args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
glauthui  |     return __callback(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_migrate/cli.py", line 149, in upgrade
glauthui  |     _upgrade(directory, revision, sql, tag, x_arg)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_migrate/__init__.py", line 98, in wrapped
glauthui  |     f(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_migrate/__init__.py", line 185, in upgrade
glauthui  |     command.upgrade(config, revision, sql=sql, tag=tag)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/alembic/command.py", line 320, in upgrade
glauthui  |     script.run_env()
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/alembic/script/base.py", line 563, in run_env
glauthui  |     util.load_python_file(self.dir, "env.py")
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
glauthui  |     module = load_module_py(module_id, path)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
glauthui  |     spec.loader.exec_module(module)  # type: ignore
glauthui  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
glauthui  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
glauthui  |   File "/home/ldap/migrations/env.py", line 25, in <module>
glauthui  |     str(current_app.extensions['migrate'].db.engine.url).replace('%', '%%'))
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
glauthui  |     return self.get_engine()
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
glauthui  |     return connector.get_engine()
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
glauthui  |     self._engine = rv = self._sa.create_engine(sa_url, options)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
glauthui  |     return sqlalchemy.create_engine(sa_url, **engine_opts)
glauthui  |   File "<string>", line 2, in create_engine
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
glauthui  |     return fn(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 560, in create_engine
glauthui  |     dbapi = dialect_cls.dbapi(**dbapi_args)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 163, in dbapi
glauthui  |     return __import__("MySQLdb")
glauthui  | ModuleNotFoundError: No module named 'MySQLdb'
glauthui  | /home/ldap/app/__init__.py:23: UserWarning: For Bootstrap 4, please import and use "Bootstrap4" class, the "Bootstrap" class is deprecated and will be removed in 3.0.
glauthui  |   bootstrap = Bootstrap(app)
glauthui  | [2023-06-18 08:51:23,920] INFO in __init__: Glauth UI
glauthui  | Traceback (most recent call last):
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
glauthui  |     return self.registry[key]
glauthui  | KeyError: <greenlet.greenlet object at 0x7f75895797c0 (otid=0x7f758720e9a0) current active started main>
glauthui  | 
glauthui  | During handling of the above exception, another exception occurred:
glauthui  | 
glauthui  | Traceback (most recent call last):
glauthui  |   File "/home/ldap/venv/bin/flask", line 8, in <module>
glauthui  |     sys.exit(main())
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask/cli.py", line 994, in main
glauthui  |     cli.main(args=sys.argv[1:])
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask/cli.py", line 600, in main
glauthui  |     return super().main(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
glauthui  |     rv = self.invoke(ctx)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
glauthui  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
glauthui  |     return ctx.invoke(self.callback, **ctx.params)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
glauthui  |     return __callback(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
glauthui  |     return f(get_current_context(), *args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask/cli.py", line 444, in decorator
glauthui  |     return __ctx.invoke(f, *args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
glauthui  |     return __callback(*args, **kwargs)
glauthui  |   File "/home/ldap/app/__init__.py", line 74, in createdbdata
glauthui  |     if models.User.query.count() == 0:
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
glauthui  |     return type.query_class(mapper, session=self.sa.session())
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
glauthui  |     sess = self.registry()
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
glauthui  |     return self.registry.setdefault(key, self.createfunc())
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4195, in __call__
glauthui  |     return self.class_(**local_kw)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
glauthui  |     bind = options.pop('bind', None) or db.engine
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
glauthui  |     return self.get_engine()
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
glauthui  |     return connector.get_engine()
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
glauthui  |     self._engine = rv = self._sa.create_engine(sa_url, options)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
glauthui  |     return sqlalchemy.create_engine(sa_url, **engine_opts)
glauthui  |   File "<string>", line 2, in create_engine
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
glauthui  |     return fn(*args, **kwargs)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 560, in create_engine
glauthui  |     dbapi = dialect_cls.dbapi(**dbapi_args)
glauthui  |   File "/home/ldap/venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 163, in dbapi
glauthui  |     return __import__("MySQLdb")
glauthui  | ModuleNotFoundError: No module named 'MySQLdb'
glauthui  | [2023-06-18 08:51:24 +0200] [1] [INFO] Starting gunicorn 20.1.0
glauthui  | [2023-06-18 08:51:24 +0200] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
glauthui  | [2023-06-18 08:51:24 +0200] [1] [INFO] Using worker: sync
glauthui  | [2023-06-18 08:51:24 +0200] [9] [INFO] Booting worker with pid: 9
glauthui  | /home/ldap/app/__init__.py:23: UserWarning: For Bootstrap 4, please import and use "Bootstrap4" class, the "Bootstrap" class is deprecated and will be removed in 3.0.
glauthui  |   bootstrap = Bootstrap(app)
glauthui  | [2023-06-18 08:51:24,870] INFO in __init__: Glauth UI`

What can I do to get it running well?

My SQL connection String in docker-compose.yml (tried all three):

`DATABASE_URL=**mysql**://<myuser>:<mypassword>@<myIP>:3306/<mydatabase>` or
`DATABASE_URL=**pymysq:**//<myuser>:<mypassword>@<myIP>:3306/<mydatabase>` or
`DATABASE_URL=**mysql+pymysql**://<myuser>:<mypassword>@<myIP>:3306/<mydatabase>` 

Additional Info: there is no SQL query arriving at the database (on different server, permissions set correctly, manual query works)

Greeting,
Magnus

**Comment by ghost** [comment]
P.S.

I tried both pulling your Docker image from git built by myself AND the prebuild one from Docker Hub
